--1) Cài partition NGAYLAP của bảng DONHANG trên CSDL ONLINE_SHOP

						--**Lưu ý**--
--Trước khi chạy tệp Partition.sql phải tạo 3 thư mục FG1, FG2, FG3 tương ứng với 3 filegroup cho NGAYLAP
--C:\PARTITION\FG1
--C:\PARTITION\FG2
--C:\PARTITION\FG3

USE ONLINE_SHOP
GO
-- tạo filegroup
ALTER DATABASE ONLINE_SHOP ADD FILEGROUP FG1
ALTER DATABASE ONLINE_SHOP ADD FILEGROUP FG2
ALTER DATABASE ONLINE_SHOP ADD FILEGROUP FG3

ALTER DATABASE ONLINE_SHOP ADD FILE (NAME = N'FG1', FILENAME=N'C:\PARTITION\FG1\FG1.ndf') TO FILEGROUP FG1
ALTER DATABASE ONLINE_SHOP ADD FILE (NAME = N'FG2', FILENAME=N'C:\PARTITION\FG2\FG2.ndf') TO FILEGROUP FG2
ALTER DATABASE ONLINE_SHOP ADD FILE (NAME = N'FG3', FILENAME=N'C:\PARTITION\FG3\FG3.ndf') TO FILEGROUP FG3
GO

CREATE PARTITION FUNCTION PF_NGAYLAP(DATE) 
AS RANGE RIGHT FOR VALUES ('01-01-2020', '01-01-2021')
GO

CREATE PARTITION SCHEME PSC_NGAYLAP
AS PARTITION PF_NGAYLAP
TO (FG1, FG2, FG3)
GO
 
CREATE NONCLUSTERED INDEX PARTITIONKEY1_IDX
ON DONHANG(NGAYLAP)
ON PSC_NGAYLAP(NGAYLAP)

GO
SELECT TONGTIEN FROM DONHANG WHERE NgayLap <='1-10-2020'