--Store Procedure
USE [ONLINE_SHOP]
GO

--select * from KHACHHANG
--select * from NHANVIEN
--select * from dbo.SANPHAM
GO
-- Đăng ký tài khoản khách hàng (Thêm khách hàng)
CREATE OR ALTER PROCEDURE SP_INS_KHACHHANG 
	@MAKH	CHAR(15),
	@HOTEN	NVARCHAR(50),
	@NGAYSINH	DATE,
	@EMAIL CHAR(50),
	@PASSWORD	NVARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON
	INSERT dbo.KHACHHANG(MAKHACHHANG, TENKHACHHANG, NGAYSINH, EMAIL, PASSWORD)
	VALUES (@MAKH, @HOTEN, @NGAYSINH, @EMAIL, @PASSWORD)
END
GO
--EXEC SP_INS_KHACHHANG 'KH1',N'KHOA','1980-02-21','KHOA@MAIL',N'123'
GO
-- Login khách hàng
CREATE OR ALTER PROCEDURE SP_LOGIN_KH @EMAIL CHAR(50), @PASSWORD NVARCHAR(100)
AS
BEGIN
	IF EXISTS (SELECT EMAIL FROM DBO.KHACHHANG WHERE EMAIL = @EMAIL)
	BEGIN
		IF EXISTS (SELECT EMAIL FROM DBO.KHACHHANG WHERE EMAIL = @EMAIL AND PASSWORD = @PASSWORD)
		BEGIN
			PRINT N'Đăng nhập thành công'
		END
		ELSE
		BEGIN
			RAISERROR(N'Mật khẩu không hợp lệ',16,1)
		END
	END
	ELSE
	BEGIN
		RAISERROR( N'Tên đăng nhập không hợp lệ',16,1)
	END
END
GO
--EXEC SP_LOGIN_KH 'nva', N'123'
GO
-- Login Nhân viên
CREATE OR ALTER PROCEDURE SP_LOGIN_NV @EMAIL CHAR(50), @PASSWORD NVARCHAR(100)
AS
BEGIN
	IF EXISTS (SELECT EMAIL FROM DBO.NHANVIEN WHERE EMAIL = @EMAIL)
	BEGIN
		IF EXISTS (SELECT EMAIL FROM DBO.NHANVIEN WHERE EMAIL = @EMAIL AND PASSWORD = @PASSWORD)
		BEGIN
			PRINT N'Đăng nhập thành công'
		END
		ELSE
		BEGIN
			RAISERROR(N'Mật khẩu không hợp lệ',16,1)
		END
	END
	ELSE
	BEGIN
		RAISERROR( N'Tên đăng nhập không hợp lệ',16,1)
	END
END

GO


-- Tim kiem san pham
CREATE OR ALTER PROCEDURE SP_FIND_SP
	@TENSP	NVARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;
	IF (@TENSP = '')
	BEGIN
		SELECT MASANPHAM, TENSANPHAM, MOTA, GIASANPHAM, SOLUONGTON AS 'SO LUONG' FROM SANPHAM
	END
	ELSE
	BEGIN
		IF EXISTS (SELECT * FROM DBO.SANPHAM WHERE TENSANPHAM = @TENSP)
		BEGIN
			SELECT MASANPHAM, TENSANPHAM, MOTA, GIASANPHAM, SOLUONGTON AS 'SO LUONG' FROM SANPHAM
			WHERE TENSANPHAM = @TENSP;
		END
	END
END
GO
--EXEC SP_FIND_SP 'Điện thoại'
GO


-- Xem ds don hang
CREATE OR ALTER PROCEDURE SP_SEL_DH
	@EMAIL	NVARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;
	
	BEGIN
		IF EXISTS (SELECT * FROM DBO.KHACHHANG WHERE EMAIL = @EMAIL)
		BEGIN
			SELECT MADONHANG, NGAYLAP, TONGTIEN, MANHANVIEN, MACUAHANG FROM DONHANG
			WHERE MAKHACHHANG = (SELECT MAKHACHHANG FROM DBO.KHACHHANG WHERE EMAIL = @EMAIL)
		END
	END
END
GO
--SELECT * FROM DONHANG
--EXEC SP_SEL_DH 'Alves695@example.com'
GO
-- Xem CT don hang
CREATE OR ALTER PROCEDURE SP_SEL_CTDH
	@MADH	NVARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;
	
	BEGIN
		IF EXISTS (SELECT * FROM DBO.CTDONHANG WHERE MADONHANG = @MADH)
		BEGIN
			SELECT * FROM CTDONHANG
			WHERE MADONHANG = @MADH
		END
	END
END
GO
--SELECT * FROM CTDONHANG
--EXEC SP_SEL_CTDH 'DH0001'
GO
-- Thống kê doanh thu
CREATE OR ALTER PROCEDURE SP_TKDT
	@NAM	NVARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;
	
	BEGIN
		Select Month(NGAYLAP) as 'Tháng', Sum(tongtien) as 'Doanh thu'
		From DONHANG
		WHERE YEAR(NGAYLAP) = @NAM
		Group by Month(NGAYLAP)
	END
END
GO
--EXEC SP_TKDT '2020'
GO
-- Quản lý tồn kho
CREATE OR ALTER PROCEDURE SP_QLTK
AS
BEGIN
	SET NOCOUNT ON;
	
	BEGIN
		SELECT MASANPHAM, TENSANPHAM, LOAISANPHAM, MANHACUNGCAP, SOLUONGTON  FROM SANPHAM
	END
END
GO
--EXEC SP_QLTK
GO

